### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by nestalee** [wildfirechat/vue-pc-chat#229]
[root@localhost vue-pc-chat]# npm run package

> wf-pc-chat@0.6.0 package /root/software/github/vue-pc-chat
> node scripts/validate.js && node scripts/del.js ./marswrapper.node && node scripts/copy-proto.js && vue-cli-service electron:build

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'md5-file'
Require stack:
- /root/software/github/vue-pc-chat/scripts/validate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at validate (/root/software/github/vue-pc-chat/scripts/validate.js:2:21)
    at Object.<anonymous> (/root/software/github/vue-pc-chat/scripts/validate.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/software/github/vue-pc-chat/scripts/validate.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wf-pc-chat@0.6.0 package: `node scripts/validate.js && node scripts/del.js ./marswrapper.node && node scripts/copy-proto.js && vue-cli-service electron:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wf-pc-chat@0.6.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-20T08_05_30_633Z-debug.log

**Comment by imndx** [comment]
执行了 ```npm install```了吗？

**Comment by nestalee** [comment]
我错了，感谢。没有用过nodejs。

**Comment by Adar-Li** [comment]
> nodejs

可以关闭问题了
